import pickle

es_ing = {
    'humanidad': 'humanity',
    'humano': 'human being',
    'persona': 'person',
    'gente': 'people',
    'hombre': 'men',
    'mujer': 'woman',
    'bebé': 'baby',
    'adolescente': 'teen',
    'caballero': 'knight',
    'dama': 'lady',
    'individuo': 'individual',
    'salud': 'health',
    'cuerpo': 'body',
    'pierna': 'leg',
    'pie': 'foot',
    'talón': 'heel',
    'espinilla': 'shin',
    'rodilla': 'knee',
    'muslo': 'thigh',
    'cabeza': 'head',
    'cara': 'expensive',
    'boca': 'mouth',
    'labio': 'lip',
    'diente': 'tooth',
    'ojo': 'eye',
    'nariz': 'nose',
    'barba': 'beard',
    'bigote': 'moustache',
    'cabello': 'hair',
    'oreja': 'ear',
    'cerebro': 'brain',
    'estómago': 'stomach',
    'brazo': 'arm',
    'codo': 'elbow',
    'hombro': 'shoulder',
    'uña': 'nail',
    'mano': 'hand',
    'muñeca': 'wrist',
    'palma': 'palm',
    'dedo': 'finger',
    'abdomen': 'abdomen',
    'hígado': 'liver',
    'músculo': 'muscle',
    'cuello': 'neck',
    'corazón': 'heart',
    'mente': 'mind',
    'alma': 'soul',
    'espíritu': 'spirit',
    'pecho': 'chest',
    'cintura': 'waist',
    'cadera': 'hip',
    'espalda': 'back',
    'sangre': 'blood',
    'carne': 'meat',
    'piel': 'skin',
    'hueso': 'bone',
    'resfriado': 'a cold',
    'gripe': 'flu',
    'diarrea': 'diarrhea',
    'enfermedad': 'illness',
    'familia': 'family',
    'colega': 'colleague',
    'pareja': 'partner',
    'matrimonio': 'marriage',
    'amor': 'love',
    'padre': 'dad',
    'madre': 'mother',
    'sobrino': 'nephew',
    'sobrina': 'niece',
    'criatura': 'creature',
    'especie': 'species',
    'ser': 'be',
    'vida': 'life',
    'nacimiento': 'birth',
    'reproducción': 'reproduction',
    'muerte': 'death',
    'geografía': 'geography',
    'naturaleza': 'nature',
    'campo': 'countryside',
    'bosque': 'forest',
    'desierto': 'desert',
    'costa': 'coast',
    'playa': 'beach',
    'río': 'river',
    'luz': 'light',
    'energía': 'energy',
    'animal': 'animal',
    'perro': 'dog',
    'gato': 'cat',
    'vaca': 'cow',
    'cerdo': 'pork',
    'oveja': 'sheep',
    'mono': 'monkey',
    'tigre': 'tiger',
    'conejo': 'rabbit',
    'dragón': 'dragon',
    'ciervo': 'deer',
    'rana': 'frog'
}

print(es_ing)

file = open('es_ingDic', 'wb')
pickle.dump(es_ing, file)
file.close()
